
--20161025
INSERT INTO [USER](CELLPHONE, EMAIL, PW, GENDER) VALUES('010-1111-8888', 'delete@naver.com', '1111', 0);

--ALTER TABLE "USER" MODIFY GENDER VARCHAR(10); 

--20161026
-- ALTER TABLE ���̺�� ADD CONSTRAINT ������Ʈ����� DEFAULT 0 FOR �ش��÷�;
ALTER TABLE [USER] ADD CONSTRAINT [uregdate] default getdate() FOR REGDATE;
ALTER TABLE [USER] ADD CONSTRAINT [uwarnning] default 0 FOR WARNING;
ALTER TABLE [POST] ADD CONSTRAINT [pregdate] default getdate() FOR REGDATE;
ALTER TABLE [POST] ADD CONSTRAINT [plike] default 0 FOR [LIKE];
ALTER TABLE [POST] ADD CONSTRAINT [phit] default 0 FOR HIT;
ALTER TABLE [COMMENT] ADD CONSTRAINT [cregdate] default getdate() FOR REGDATE;
ALTER TABLE [TAG] ADD CONSTRAINT tcodede default 1 FOR CODE;
ALTER TABLE [TAG] ADD CONSTRAINT tcodech CHECK (CODE BETWEEN 1 AND 7);

SELECT * FROM [USER];
SELECT * FROM POST; 
SELECT * FROM COMMENT;
SELECT * FROM TAG;
SELECT * FROM USER_COMMENT_VIEW;

DROP TABLE USER_COMMENT;

DELETE FROM [USER];
DELETE FROM POST;
DELETE FROM COMMENT;
DELETE FROM TAG;

-- INSERT INTO [���̺��] ([�÷���]) VALUES ([��]) 
INSERT INTO [USER](CELLPHONE, EMAIL, PW, GENDER) VALUES('010-1111-8888', 'delete@naver.com', '1111', 'M');
INSERT INTO [USER](CELLPHONE, EMAIL, PW, GENDER) VALUES('010-1234-5678', 'test@naver.com', '1234', 'W');
INSERT INTO POST(PHOTO, STORY,CODE EMAIL, ) VALUES('����', '���躸�� ��忡 ���Դµ�,������ �ʹ� ����.����� �׳� �𷧹ٴ��̾��ٸ� �� �ܲ����� �ٵ� ����!', 'test@naver.com', 1);
INSERT INTO COMMENT(CODE, CONTENT, EMAIL, POST_CODE) VALUES(1, '���� ���� �þ��!�� �������� �� �� �� �ſ���!', 'test@naver.com', 1);
INSERT INTO COMMENT(CODE, CONTENT, EMAIL, POST_CODE) VALUES(2, '������ :)', 'test@naver.com', 1);
INSERT INTO TAG(CODE, [NAME], POST_CODE) VALUES(1, '#GREEN', 1);
INSERT INTO TAG(CODE, [NAME], POST_CODE) VALUES(2, '#TOEIC', 1);
INSERT INTO TAG(CODE, [NAME], POST_CODE) VALUES(3, '#���', 1);
INSERT INTO TAG(CODE, [NAME], POST_CODE) VALUES(4, '#����', 1);
INSERT INTO TAG(CODE, [NAME], POST_CODE) VALUES(5, '#�ʷϻ�', 1);
INSERT INTO TAG(CODE, [NAME], POST_CODE) VALUES(6, '#��ŭ��', 1);
INSERT INTO TAG(CODE, [NAME], POST_CODE) VALUES(8, '#?', 1);

--USER COMMENT VIEW
CREATE VIEW USER_COMMENT_VIEW AS
SELECT U.GENDER, C.CODE, C.CONTENT, C.EMAIL, C.POST_CODE, C.REGDATE
FROM [USER] U RIGHT OUTER JOIN COMMENT C
ON U.EMAIL = C.EMAIL;

--WHERE ���� SELECT���� ���� �����ϹǷ� ���������� BETWEEN 1 AND 10
--���������� �ݵ�� ��Ī�� �����
SELECT * FROM 
(
SELECT ROW_NUMBER() OVER (ORDER BY REGDATE DESC) NUM, USER_COMMENT_VIEW.* 
	FROM USER_COMMENT_VIEW
	WHERE POST_CODE = 1
) C WHERE NUM BETWEEN 1 AND 10;


SELECT * FROM
		(
		SELECT ROW_NUMBER() OVER (ORDER BY REGDATE DESC) NUM, USER_COMMENT_VIEW.*
		FROM USER_COMMENT_VIEW
		WHERE POST_CODE = 
		) C

