select * from post
--20161025
INSERT INTO [USER](CELLPHONE, EMAIL, PW, GENDER) VALUES('010-1111-8888', 'delete@naver.com', '1111', 0);

--ALTER TABLE "USER" MODIFY GENDER VARCHAR(10); 

--20161026
-- ALTER TABLE ���̺�� ADD CONSTRAINT ������Ʈ����� DEFAULT 0 FOR �ش��÷�;
ALTER TABLE [USER] ADD CONSTRAINT [uregdate] default getdate() FOR REGDATE;
ALTER TABLE [USER] ADD CONSTRAINT [uwarnning] default 0 FOR WARNING;
ALTER TABLE [POST] ADD CONSTRAINT [pregdate] default getdate() FOR REGDATE;
ALTER TABLE [POST] ADD CONSTRAINT [plike] default 0 FOR [LIKE];
ALTER TABLE [POST] ADD CONSTRAINT [phit] default 0 FOR HIT;
ALTER TABLE [COMMENT] ADD CONSTRAINT [cregdate] default getdate() FOR REGDATE;
ALTER TABLE [TAG] ADD CONSTRAINT tcodede default 1 FOR CODE;
ALTER TABLE [TAG] ADD CONSTRAINT tcodech CHECK (CODE BETWEEN 1 AND 7);

SELECT * FROM [USER];
SELECT * FROM POST; 
SELECT * FROM COMMENT;
SELECT * FROM TAG;
SELECT * FROM USER_COMMENT_VIEW;

DROP TABLE USER_COMMENT;

DELETE FROM [USER];
DELETE FROM POST;
DELETE FROM COMMENT;
DELETE FROM TAG;

-- INSERT INTO [테이블명] ([컬럼명]) VALUES ([값]) 
INSERT INTO [USER](CELLPHONE, EMAIL, PW, GENDER) VALUES('010-1111-8888', 'delete@naver.com', '1111', 'M');
INSERT INTO [USER](CELLPHONE, EMAIL, PW, GENDER) VALUES('010-1234-5678', 'test@naver.com', '1234', 'W');
INSERT INTO POST(STORY, EMAIL, CODE) VALUES('시험보고 운동장에 나왔는데,날씨가 너무 좋다.운동장이 그냥 모랫바닥이었다면 더 꿀꿀했을 텐데 다행!', 'test@naver.com', 1);
INSERT INTO COMMENT(CODE, CONTENT, EMAIL, POST_CODE) VALUES(1, '저도 오늘 봤어요!ㅠ 다음에는 더 잘 볼 거예요!', 'test@naver.com', 1);
INSERT INTO COMMENT(CODE, CONTENT, EMAIL, POST_CODE) VALUES(2, '힘내요 :)', 'test@naver.com', 1);
INSERT INTO TAG(CODE, [NAME], POST_CODE) VALUES(1, '#GREEN', 1);
INSERT INTO TAG(CODE, [NAME], POST_CODE) VALUES(2, '#TOEIC', 1);
INSERT INTO TAG(CODE, [NAME], POST_CODE) VALUES(3, '#운동장', 1);
INSERT INTO TAG(CODE, [NAME], POST_CODE) VALUES(4, '#망했', 1);
INSERT INTO TAG(CODE, [NAME], POST_CODE) VALUES(5, '#초록색', 1);
INSERT INTO TAG(CODE, [NAME], POST_CODE) VALUES(6, '#상큼해', 1);
INSERT INTO TAG(CODE, [NAME], POST_CODE) VALUES(8, '#?', 1);


	INSERT INTO [USER] (CELLPHONE, EMAIL, PW, GENDER) 
			VALUES('010-1111-1111', '12df@naver.com', 'adsf', 'df')

--USER COMMENT VIEW
CREATE VIEW USER_COMMENT_VIEW AS
SELECT U.GENDER, C.CODE, C.CONTENT, C.EMAIL, C.POST_CODE, C.REGDATE
FROM [USER] U RIGHT OUTER JOIN COMMENT C
ON U.EMAIL = C.EMAIL;

--WHERE ���� SELECT���� ���� �����ϹǷ� ���������� BETWEEN 1 AND 10
--���������� �ݵ�� ��Ī�� �����
SELECT * FROM 
(
SELECT ROW_NUMBER() OVER (ORDER BY REGDATE DESC) NUM, USER_COMMENT_VIEW.* 
	FROM USER_COMMENT_VIEW
	WHERE POST_CODE = 1
) C WHERE NUM BETWEEN 1 AND 10;


SELECT * FROM
		(
		SELECT ROW_NUMBER() OVER (ORDER BY REGDATE DESC) NUM, USER_COMMENT_VIEW.*
		FROM USER_COMMENT_VIEW
		WHERE POST_CODE = 
		) C

